seo:
  site_name: ProActiverz | Gabriel Iulian Balu
  title: ProActiverz | Gabriel Iulian Balu
  description: >-
    Vorbim despre dezvoltare personala, educatie financiara pe bune. Vorbim
    despre cum poti ajunge cea mai buna versiune a ta. Vorbim despre valori,
    obiceiuri, rutine, carti, mentori. Vorbim despre investitii la bursa,
    investitii in ETF-uri, investitii in bitcoin, crypto si multe altele.

    Tot ce ai nevoie pentru a te dezvolta eficient pe toate planurile, la un
    click distanta!
  keywords: >-
    proactiverz, gabriel balu, proactiverz dezvoltare personala, proactiverz
    educatie financiara, cum sa faci bani, investitii la bursa, investitii in
    crypto, dezvoltare personala carti, dezvoltare personala copii, dezvoltare
    profesionala, succesul definitie, succesul profesional, cum sa ai succes,
    cum sa iti schimbi viata, educatie financiara bursa, educatie financiara
    pentru copii, educatie financiara carti, educatie financiara romania, cum sa
    faci bani online, cum sa faci bani de acasa, ebook educatie financiara,
    investitii in actiuni, investitii pe termen scurt, investitii imobiliare,
    investitii 2022, investitii profitabile, investeste la bursa, investeste in
    tine, investeste in actiuni, investeste in crypto, investeste in
    cryptomonede, investeste in etf, investeste in aur, investeste in active,
    investitii in criptomonede 2022, investitii in criptomonede pareri,
    investitii in criza, investitii in criza economica, investitii crypto 2022,
    despre investitii in criptomonede, investitii bursa, investitii bitcoin,
    investitii bvb, investitii bursa 2022, investitii bursa informatii
social:
  instagram_url: https://www.instagram.com/proactiverz/
  facebook_url: https://www.facebook.com/ProActiverzOn
  tiktok_url: https://www.tiktok.com/@gabrielbalu24
  youtube_url: https://www.youtube.com/c/ProActiverz1/featured
  email_address: gabriel@proactiverz.ro