seo:
  site_name: Gabriel Iulian Balu
  title: Gabriel Iulian Balu
  description:
  keywords:
social:
  instagram_url: https://www.instagram.com/
  facebook_url: https://www.facebook.com/
  tiktok_url: https://www.tiktok.com/
  youtube_url: https://www.youtube.com/