seo:
  site_name: Gabriel Iulian Balu
  title: Gabriel Iulian Balu
  description:
  keywords:
social:
  instagram_url: https://www.instagram.com/proactiverz/
  facebook_url: https://www.facebook.com/ProActiverzOn
  tiktok_url: https://www.tiktok.com/@gabrielbalu24
  youtube_url: https://www.youtube.com/c/ProActiverz1/featured
  email_address: gabriel@proactiverz.ro